### ISSUE TITLE
iFrame doesn't work on Github Pages

### ISSUE THREAD

**Issue by danrademacher** [cityenergyproject/saltlakecity#3]
Something's wrong with the iFrame on the GH pages deployment both here and in the main City Energy repo. Sample that should work (and works locally): http://cityenergyproject.github.io/saltlakecity/iframe.html

Error:
![image](https://cloud.githubusercontent.com/assets/1423200/11104295/a83e3160-887c-11e5-99d2-771f09eab046.png)

The code is looking for http://cityenergyproject.github.io/app/main.js but should be looking for http://cityenergyproject.github.io/saltlakecity/app/main.js.

Seems the path to the main JS code is broken here:
https://github.com/cityenergyproject/saltlakecity/blob/master/src/iframe.html#L23

``` html
 <script src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.1.19/require.js" data-main="../app/main"></script>
```

That works locally whether it's `../app/main` or `/app/main`, but neither works on GH Pages.

Logically, it would seem that `/saltlakecity/app/main` would work on GH Pages, but it definitely doesn't work locally, and I'm loathe to just shove it up there and see... There must be a smarter solution here.

**Comment by sethfitz** [comment]
A relative path (same as in `index.html`) ended up being the solution. Removed the "Los Angeles" copy by default, in favor of having it fed by the config.
